// type constant for gist type api
export const GIST_ACTION_TYPES = {
  GET_ALL_USERS: "GET_ALL_USERS",
  ALL_USER_SUCCESS: "ALL_USER_SUCCESS",
  ALL_USER_FAILED: "ALL_USER_FAILED",

  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  LOADER: "LOADER"
};
